# Site settings
title: Vijay Vankhede # site title
description: >- # site description
  Android | Kotlin | Problem Solving
lang: en-US # default lang
timezone: Asia/Kolkata # set your timezone
image: assets/img/ogp.jpg # This image used for Open Graph more info https://ogp.me/
repo: https://github.com/vsvankhede/jekyll-klise # site repo [optional]
mode: light # default theme "dark" | "light"

# Profile settings
author:
  name: Vijay Vankhede # author name
  bio: >- # tell to the world
    Android | Kotlin | Problem Solving
  username: vsvankhede # social media username eg. github, twitter 
  email: vijay.s.vankhede@gmail.com # your contact adress
  avatar: /assets/img/avatar.jpg # change with your own avatar

# Url settings
url: "https://lucid-mestorf-7bb5ab.netlify.app"
baseurl:
permalink: /:title/
google_analytics:
fb_appid:

# Collection setting
collections:
  posts:
    output: true

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: post
      comments: false

# Jekyll Compose default front matter
jekyll_compose:
  post_default_front_matter:
    modified:
    tags: []
    description:
  draft_default_front_matter:
    modified:
    tags: []
    description:

# Build settings
sass:
  style: compressed

include:
  - _redirects
  - .htaccess

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CHANGELOG.md
  - README.md
  - node_modules
  - CODE_OF_CONDUCT.md

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-postfiles
